---
- hosts: "{{ servers | default('localhost') }}"
  gather_facts: yes
  become: no
  tasks:
  - debug:
      msg: "{{ lookup('env', 'VAULT_ROLE_ID') }}"
  - debug:
      msg: "{{ lookup('hashi_vault', 'secret=kv/liadsh')}}"
